"""Version changelog — pure data, zero coupling."""
CHANGELOG = [
    ("10.13.8", "2026-05-27", [
        "Fix: force_finalize skips Gemini call entirely (was hallucinating tool calls without tools)",
        "Fix: _send_ag_finalize returns status=failed (was stored as valid history causing loops)",
        "Fix: _forward_gemini_sse wrapped in try/except for TimeoutError/BrokenPipe",
        "Fix: file tracker mutations inside lock scope (was racing in ThreadingHTTPServer)",
        "Fix: compaction summary strips raw tool outputs (was re-triggering read loops)",
        "Fix: post-compaction write directive when 10+ reads with 0 writes",
        "Fix: detect get_goal/completion_budget null-tool loops (3+ → force finalize)",
        "Fix: read-loop threshold raised to 8 same-file / 40 total (was too aggressive at 5/30)",
        "Fix: strip timestamps from loop hash, base64 image data from normalizer",
    ]),
    ("3.12.1", "2026-05-27", [
        "Fix Antigravity adapter (PR #15): simplify model resolution",
        "Removed broken schema sanitization, restored correct headers",
        "Expanded model alias map for all Antigravity variants",
        "Re-enabled gRPC fallback by default",
    ]),
    ("3.12.0", "2026-05-27", [
        "gRPC auto-fallback for Antigravity provider (PR #13)",
        "New antigravity_grpc module with protobuf client",
        "REST 404 triggers gRPC fallback using display names",
        "gRPC supports streaming and unary generate",
        "Dynamic version fetch with probe validation",
        "Antigravity v2 handler rewrite (anti-api approach)",
        "Safety settings, stopSequences, sessionId, requestType: agent",
    ]),
    ("3.11.11", "2026-05-26", [
        "Final trimming only removes plain messages, never function_call_output",
    ]),
    ("3.11.10", "2026-05-26", [
        "Fix Antigravity: interleave function_call/output pairs in correct sequence (PR #11)",
        "Fix Gemini sanitizer: trim leading/trailing non-user turns for Google API compliance",
        "Stricter function call/response isolation — no merging across role boundaries",
    ]),
    ("3.11.9", "2026-05-26", [
        "Fix Antigravity: preserve functionCall/functionResponse in Gemini sanitizer (PR #10)",
        "Prevents tool responses from being merged/dropped in multi-turn Antigravity sessions",
    ]),
    ("3.11.8", "2026-05-26", [
        "Vision description cache persisted across requests (no redundant API calls for same image)",
        "Merge PR #8: fix vision cache persistence across requests",
    ]),
    ("3.11.7", "2026-05-26", [
        "Vision auto-detect: uses provider's own vision model (e.g. 0G-Qwen-VL) as fallback for image description",
        "Vision preprocessing replaces image stripping: images described via API instead of just removed",
        "Fix AttributeError in image_url handling when value is string not dict",
        "Merge PR #6: vision/OCR preprocessing for text-only models",
        "Merge PR #7: 177 unit tests for translate-proxy.py",
        "Auth os error 2 fix: GUI shows config-missing message instead of raw error",
    ]),
    ("3.11.6", "2026-05-26", [
        "Antigravity loop breakers: per-session tracking, edit-intent nudge (first turn only)",
        "Loop breaker: same tool+args repeated 5+ times triggers force finalization",
        "Latest user instruction appended exactly once per request",
        "Detailed [antigravity-loop] logging for all tracking fields",
        "has_content fix: function_call now counts as valid output (no more infinite loops)",
        "Antigravity-only changes, no touch to other providers",
    ]),
    ("3.11.5", "2026-05-26", [
        "Token-aware compaction: fixes context_length_exceeded on small-context models (25 items x 1600 tokens)",
        "Proactive compaction triggers on token count (>80% model limit), not just item count",
        "Universal adaptive compaction: removed crof.ai-only gates, all providers get compaction",
        "Vision model detection: strips images for non-vision models, keeps for vision-capable ones",
        "Per-model token limit learning from context_length_exceeded error messages",
        "Compaction aggression levels: normal vs extreme when tokens > 1.5x model limit",
        "Smart-continue text-tool detection: triggers on tool-call text patterns, not just function_call_output",
        "Active endpoint sync: GUI auto-removes stale endpoint references on startup",
    ]),
    ("3.11.0", "2026-05-26", [
        "Merge cobra PR: concurrency semaphore (max 3), auto-continue for truncated text",
        "SO_REUSEADDR on sticky port, proxy-stderr.log, stream diagnostics logging",
        "Timeout/OSError handler sends response.failed SSE instead of silent drop",
        "Restart Proxy button: only restarts proxy without killing Codex Desktop",
        "Tool call argument normalizer: fixes Arguments->arguments, strips markdown wrapping",
        "Smart-continue loop (2x retries): escalating nudges when model stops text-only mid-task",
        "XML tool call extraction: parses patterns from text, injects as real calls",
        "Auto-continue + smart-continue ordered with skip guard to avoid double-firing",
        "API key hot-reload with mtime tracking + /admin/reload + /admin/verify-key endpoints",
        "GUI hot-reload: auto-refreshes proxy key on endpoint edit, verifies with upstream",
        "Synthetic tool-results disabled: was causing deepseek-v4-pro truncation on opencode.ai",
    ]),
    ("3.10.12", "2026-05-26", [
        "Sticky endpoint: caches last working endpoint, sequential fallback on failure",
        "Endpoint order: cloudcode-pa first (matches agy CLI), daily-cloudcode-pa fallback",
        "Anti-stall engine: kills stale proxy processes + clears pycache on startup",
        "Smart error classification: quota vs capacity vs banned vs validation vs auth",
        "Rate limit reset parsing: extracts cooldown from error body for accuracy",
        "Missing headers: X-Client-Name, X-Client-Version, x-goog-api-client, sessionId",
        "Guardrail skip: simple messages (hi) skip agent guardrail, no more tool-call loops",
        "Claude fixes: preserve all tools, skip compaction/normalizer/sanitization for Claude",
        "Normalizer model param: distinguishes Claude vs Gemini for correct behavior",
    ]),
    ("3.10.11", "2026-05-26", [
        "Hybrid endpoint fallback: cloudcode-pa then daily-cloudcode-pa on 429",
        "daily-cloudcode-pa.googleapis.com (same endpoint agy-core uses)",
        "429 errors log full response body for debugging",
        "Rate-limit marking only after ALL endpoints fail",
        "Restored SERVICE_DISABLED (403) fallthrough",
    ]),
    ("3.10.10", "2026-05-25", [
        "Fix normalizer stripping ALL context after compaction on resumed sessions",
        "No auto-reset when compaction summary present (preserves 1925+ turn history)",
        "Always preserve compaction summaries in normalizer output",
        "Deduplicate consecutive identical goal_context messages",
        "Emergency reset preserves compaction summaries",
        "Fix hashlib NameError in _antigravity_normalize_context (string comparison instead)",
    ]),
    ("3.10.9", "2026-05-25", [
        "Antigravity: production-only endpoints (cloudcode-pa.googleapis.com), sandbox blocked unless ALLOW_ANTIGRAVITY_STAGING=1",
        "Antigravity: 403 SERVICE_DISABLED falls through, 429 returns to client (no sandbox fallback)",
        "AntigravityContextNormalizer: bounded context — simple messages send minimal payload",
        "Simple message detector: 'hi' etc sends only user message, no tool history",
        "Auto-reset polluted context: 200+ items with simple message resets to minimal",
        "Duplicate user message removal, tool output budget (max 2 verbatim, rest summarized)",
        "Hard limits: 20 contents, 120K/250K/500K char budgets",
        "Claude thinking fix: maxOutputTokens=64000, snake_case thinking config, VALIDATED toolConfig",
        "Claude budgets: low=8192, medium=16384, high=32768",
        "All fixes scoped to OAUTH_PROVIDER==google-antigravity only",
        "Project discovery uses production endpoint (not staging)",
        "z.ai: full OpenClaw attribution headers (cobra91 PR #4)",
        "OpenRouter: X-OpenRouter-Cache header (cobra91 PR #4)",
        "Fix Linux Re-OAuth: load_oauth_secrets() was undefined",
        "Fix GLib.idle_add lambda returning truthy tuple",
    ]),
    ("3.10.7", "2026-05-25", [
        "Prompt Enhancer: per-provider toggle to improve prompt clarity after compaction",
        "Two modes: offline (template injection) and ai-powered (external LLM rewrites)",
        "Offline mode: injects structured instructions to keep model focused post-compaction",
        "AI-powered mode: uses configurable model/URL/key to rewrite prompts for clarity",
        "Linux/Windows GUI: Prompt Enhancer switch + mode selector + model/URL/key fields",
        "Prevents lost context issues in long sessions with aggressive compaction",
    ]),
    ("3.10.6", "2026-05-25", [
        "Freebuff integration: free DeepSeek/Kimi via codebuff.com API",
        "Fixed Freebuff User-Agent to match official SDK (ai-sdk/openai-compatible/1.0.25/codebuff)",
        "Fixed Freebuff metadata: freebuff_instance_id + client_id (base36) + cost_mode: free",
        "Fixed Codebuff OAuth: use www.codebuff.com (307 redirect on bare domain)",
        "GUI preset aliases: Freebuff, FreeBuff, Codebuff all map to same backend",
        "Windows GUI consolidated into src/ (merged by cobra91)",
        "CROF adaptive logic gated to crof.ai only — no log pollution for other providers",
        "Data dir consolidation: all data in codex-proxy/",
        "Sticky proxy port: persists in .last-proxy-port for restart persistence",
        "Adaptive compact budget raised 60% to 80% for large-context models",
        "Config cleanup fix: stale proxy-*.json moved after _init_runtime()",
        "Windows GUI: Clear Log, Restart Proxy, View Log buttons (cobra91 PR #3)",
        "OAuth Secrets dialog shows all providers: Google + Freebuff/Codebuff",
        "Re-OAuth buttons for each provider: re-authenticate Google or GitHub/Codebuff",
        "Token status indicators (valid/missing) for each Google provider",
        "Shows logged-in email and auth status for Freebuff/Codebuff",
        "Linux/Windows feature parity: both GUIs have identical features",
        "Windows: OAuth Secrets all-providers + Codebuff OAuth + Sync from Preset",
        "Linux: Clear Log + Restart Proxy buttons added",
    ]),
    ("3.10.5", "2026-05-25", [
        "Context compaction for Antigravity/Gemini OAuth — prevents token limit errors",
        "Aggressive compaction policies at 60% of model context limit",
        "Compaction for cloudcode-pa and googleapis provider policies",
        "REST model IDs added to context size map (gemini-3-flash, etc.)",
        "OAuth Secrets editor in GUI — update client ID/secret without editing files",
        "Secrets stored in ~/.config/codex-launcher/oauth-secrets.json (not in repo)",
        "Import JSON button — import client_secret_*.json from Google Cloud Console",
        "All hardcoded OAuth secrets removed from source code",
        "Antigravity model IDs fixed: display names → slug model IDs for REST API",
        "Git history scrubbed of leaked credentials; pre-push hook installed",
        "Antigravity REST API model IDs verified with live API testing",
        "Gemini 3.5 Flash, 3.1 Pro, Claude 4.6, GPT-OSS 120B all working",
    ]),
    ("3.9.9", "2026-05-25", [
        "Refresh Antigravity preset: Gemini 3.5 Flash, Gemini 3.1 Pro, Claude 4.6, GPT-OSS",
        "Fix Antigravity alias map for tiered model IDs (high/medium/low/thinking)",
        "Model context sizes for Gemini 3.5 Flash, 3.1 Pro, Claude 4.6, GPT-OSS 120B",
    ]),
    ("3.9.8", "2026-05-25", [
        "Fix Desktop model leak — remap gpt-5.4-mini to user-selected model",
        "send_json() catches BrokenPipeError globally — no crashes on disconnect",
        "Proxy remaps Desktop forced models via CODEX_LAUNCHER_MODEL env",
    ]),
    ("3.9.7", "2026-05-25", [
        "Forward real Codebuff error messages instead of generic 429",
        "Return HTTP 200 with Responses API format for rate limits",
        "Extract retryAfterMs from Codebuff 429 responses for cooldown",
        "RateLimitError carries upstream message through all paths",
        "BrokenPipeError fix on 'all accounts exhausted' response",
        "Fix 3 SyntaxWarnings for invalid escape sequences",
        "_codebuff_start_run returns actual error body",
    ]),
    ("3.9.6", "2026-05-25", [
        "Fix Gemini follow-up turns: enforce latest user instruction as final turn",
        "Edit-intent detection with tool-use nudge for file modifications",
        "Thought signature preservation for Gemini 3 tool-call continuity",
        "Smart tool output compaction: old=3000, recent=20000 chars",
        "Multi-account rotation for codebuff, Google OAuth, API keys",
        "/v1/accounts endpoint for account pool status",
    ]),
    ("3.9.0", "2026-05-24", [
        "Multi-account rotation for OAuth providers (codebuff, Google, API keys)",
        "Automatic failover on rate limit — next account used",
        "Codebuff: accounts[] array in credentials.json",
        "Google OAuth: multiple token files (google-*-oauth-token-N.json)",
        "API keys: comma-separated keys rotate on 429 errors",
        "/v1/accounts endpoint shows account pool status",
        "x-codebuff-model and x-codebuff-instance-id headers",
    ]),
    ("3.8.4", "2026-05-24", [
        "Codebuff streaming — SSE events reach Codex client",
        "stream_buffered_events now called for codebuff",
        "Codebuff OAuth built-in login flow (no external CLI)",
        "Codebuff API: reverse-engineered www.codebuff.com endpoints",
        "Codebuff session management with instance ID",
        "Codebuff agent run lifecycle (start/finish) with model routing",
        "Free DeepSeek V4 Pro, V4 Flash, Kimi K2.6, MiniMax M2.7",
        "Reasoning mode works with codebuff (thinking tokens supported)",
        "GUI: Sandbox mode selector (Read-only / Workspace / Full Access)",
        "GUI: Approval mode selector (Untrusted / On Request / Full Auto)",
        "GUI: Codebuff Login button in endpoint editor",
    ]),
    ("3.8.1", "2026-05-24", [
        "Freebuff integration — free DeepSeek V4 Pro, V4 Flash, Kimi K2.6, MiniMax M2.7",
        "Freebuff backend: auto agent-run lifecycle, credential detection, model routing",
        "Restored all provider presets (Command Code, Crof, OpenAdapter, OpenRouter, etc.)",
        "AI Monitoring — self-healing watchdog with 3-tier response system",
        "HealthWatcher: monitors proxy health every 5s, auto-restarts on crash",
        "LogAnalyzer: tails debug logs for 18 failure signal patterns",
        "Tier 1: 14 rule-based auto-recovery rules (< 1 s response)",
        "Tier 2: Incident pattern store with success rate tracking",
        "Tier 3: AI diagnostic agent — configurable provider/model for novel failures",
        "30 fault types catalogued across 5 categories (A-E)",
        "GUI: AI Monitor panel with ON/OFF, provider selector, incident log",
        "Enhanced /health endpoint with memory and uptime metrics",
    ]),
    ("3.7.0", "2026-05-22", [
        "Intelligence Routing — self-healing parser system for Command Code",
        "Layer 1: Deep URL extraction from nested JSON in explore_agent blocks",
        "Layer 2: Auto-proceed on require_escalation / request_escalation_permission blocks",
        "Layer 3: Intent-based command synthesis when all parsers fail (5 heuristics)",
        "Module-level _build_explore_cmd() — reuses URL extraction across parser + stream",
        "54 self-test patterns covering all three Intelligence Routing layers",
    ]),
    ("3.6.0", "2026-05-22", [
        "Connection pooling — persistent HTTPS connections per host",
        "Stream idle timeout (300s) — kills silent streams instead of hanging",
        "Retry-After header support on all retry paths",
        "Bounded stream buffers (8MB) — prevents OOM",
        "Dual logging to proxy.log + stderr",
    ]),
    ("3.5.0", "2026-05-22", [
        "Command Code adapter overhaul — 17 patches for multi-format tool-call parsing",
        "DSML, XML, explore_agent, bash blocks, raw JSON parser chain",
        "Self-revive watchdog — auto-restarts proxy on crash",
        "Debug-to-file logging in cc-debug.log",
        "Inline self-test (19 patterns)",
    ]),
    ("3.3.0", "2026-05-20", [
        "Antigravity + Gemini CLI OAuth — full Codex agent loop working",
        "Auto-continue on MAX_TOKENS for Gemini/Antigravity",
        "BGP++ route scoring and provider policy layer",
    ]),
    ("3.0.0", "2026-05-20", [
        "Major overhaul — ThreadingHTTPServer, thread-safe state, graceful shutdown",
        "Dynamic port allocation, proxy health gating, atomic config",
        "Usage Dashboard v2 with dark theme",
    ]),
    ("2.7.0", "2026-05-20", [
        "Usage Dashboard redesigned (OpenUsage-inspired dark theme)",
        "TCP_NODELAY streaming, Anthropic prompt caching",
    ]),
    ("2.6.1", "2026-05-20", [
        "Google OAuth rebuilt to emulate Gemini CLI — no client_secret.json needed",
        "Uses Google's public OAuth client_id (same as gemini-cli)",
        "PKCE + CSRF state protection for secure auth",
        "Just click OAuth Login — browser opens — authorize — done",
        "Includes cloud-platform scope for Gemini Code Assist compatibility",
    ]),
    ("2.6.0", "2026-05-20", [
        "Usage Dashboard — per-provider request/token/latency tracking",
        "Visual cards with success rate bars, model breakdown, error tracking",
        "Google OAuth: browse for client_secret.json instead of fixed path",
    ]),
    ("2.5.1", "2026-05-20", [
        "Adaptive retry for 429/502/503 errors with exponential backoff",
        "BGP routes also retry transient errors before failing over",
        "Proxy socket reuse — no more 'Address already in use' crashes",
        "BGP route count shown at proxy startup",
    ]),
    ("2.5.0", "2026-05-20", [
        "AI BGP — multi-provider routing with automatic failover",
        "Create BGP pools with ordered routes from any configured endpoint",
        "Each route uses its own endpoint URL, API key, and model",
        "Failover strategy: tries primary, falls back on error/timeout",
        "BGP pools appear in endpoint dropdown with shuffle icon",
        "Up/down reordering for route priority in pool editor",
        "Fixed TOML config breakage from multi-line paste in fields",
    ]),
    ("2.4.0", "2026-05-20", [
        "Added OpenAdapter provider preset (api.openadapter.in)",
        "One API key access to 40+ models — GLM, DeepSeek, Kimi, Qwen, Claude, GPT, Gemini",
        "Fixed Add/Edit dialog crash (missing _on_reasoning_toggled method)",
        "Redesigned Google OAuth flow with live status dialog",
    ]),
    ("2.3.2", "2026-05-20", [
        "Added Google Gemini provider with OAuth support",
        "Two presets: 'Google Gemini (API Key)' and 'Google Gemini (OAuth)'",
        "OAuth Login button in endpoint editor — full Google OAuth2 flow with auto-refresh",
        "Auto-refreshes OAuth access tokens when expired (no manual re-login needed)",
        "Supports gemini-2.5-flash, gemini-2.5-pro, gemini-2.0-flash, and more",
        "Uses Gemini's OpenAI-compatible endpoint — works with existing proxy",
    ]),
    ("2.3.0", "2026-05-20", [
        "Adaptive Crof self-healing system — auto-adjusts to Crof model limits",
        "Tracks per-model success/failure history, learns item count limits dynamically",
        "Proactively compacts input when above learned limit before sending to Crof",
        "Auto-retries on finish_reason=length — aggressively compacts and resends",
        "Prevents 'stream disconnected' and 'incomplete' errors on long conversations",
    ]),
    ("2.2.1", "2026-05-20", [
        "Fixed compaction orphaning function_call_output items — root cause of Crof incomplete responses",
        "Compaction now respects function_call/function_call_output pairs — no more dangling tool results",
        "Fixed reasoning control: reasoning_effort=none now always sends enable_thinking=false too",
    ]),
    ("2.2.0", "2026-05-20", [
        "Added per-provider Reasoning On/Off toggle in endpoint editor",
        "Added Reasoning Effort level per provider: None, Minimal, Low, Medium, High, Max",
        "When reasoning is OFF: sends enable_thinking=false + reasoning_effort=none to upstream API",
        "When reasoning is ON: sends user-selected effort level (default: Medium)",
        "Fixes Crof mimo-v2.5-pro and similar reasoning models exhausting output tokens",
        "Strip reasoning_content from proxy output — Codex doesn't use it",
        "Force max_tokens=64000 minimum for openai-compat providers",
    ]),
    ("2.1.3", "2026-05-19", [
        "Fixed Crof mimo-v2.5-pro stopping: reasoning_content exhausted all output tokens",
        "Strip reasoning_content from proxy output — Codex doesn't use it, avoids token waste",
        "Force max_tokens=64000 minimum for openai-compat providers",
    ]),
    ("2.1.2", "2026-05-19", [
        "Fixed Crof.ai and providers stopping after first tool call (root cause: None tool IDs)",
        "Codex sends function_call items with id=None — proxy now matches tool results to calls by position",
        "Fixed orphan message output item when response has only tool calls (no text)",
        "Auto-trims long conversations (>30 items) to prevent context overflow on providers like Crof",
        "Added request/response logging to ~/.cache/codex-proxy/requests.log",
    ]),
    ("2.1.1", "2026-05-19", [
        "Fixed proxy: map 'developer' role to 'system' for Chat Completions providers",
        "Fixed proxy: map 'developer' role to 'user' for Anthropic providers",
        "Forward 'instructions' field from Responses API as system message/param",
        "Fixes DeepSeek and other providers rejecting unknown 'developer' role",
    ]),
    ("2.1.0", "2026-05-19", [
        "Added Codex auth status detection (codex login status)",
        "Added Re-login button to re-authenticate via codex login",
        "Auto-checks auth before launching Codex Default mode",
        "Warns if OAuth token expired or missing before launch",
    ]),
    ("2.0.1", "2026-05-19", [
        "Added Codex CLI/Desktop installation verifier to main page",
        "Disables Desktop/CLI launch buttons when corresponding tool is missing",
        "Shows install instructions in status area on startup",
    ]),
    ("2.0.0", "2026-05-19", [
        "Initial release: multi-provider Codex Launcher",
        "Translation proxy: Responses API to Chat Completions + Anthropic Messages",
        "GTK endpoint manager with 10+ provider presets",
        "Codex Default mode (built-in OAuth, zero config)",
        "Browser UA injection for Cloudflare-protected providers (OpenCode)",
        "Streaming SSE, tool calls, reasoning content support",
        "Profile backup/import, model auto-fetch, bulk import",
        "Refresh Models in background thread",
        "URL normalization to prevent double-path bugs",
        "Config backup/restore around sessions",
        ".deb installer package",
    ]),
]
